# Generated by Django 4.1.3 on 2022-11-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userresponders_businesresponders'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondersForBusines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.busines')),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.muser')),
            ],
        ),
        migrations.CreateModel(
            name='RespondersForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.busines')),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.muser')),
            ],
        ),
        migrations.RemoveField(
            model_name='userresponders',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userresponders',
            name='vacancy',
        ),
        migrations.DeleteModel(
            name='BusinesResponders',
        ),
        migrations.DeleteModel(
            name='UserResponders',
        ),
    ]
