# Generated by Django 4.1.3 on 2022-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_respondersforuser_b_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busines',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
