# Generated by Django 4.1.3 on 2022-11-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_userachive'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
